
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (1,'Super Mario Bros.','Nintendo',1985,9.5,'Common','Easy');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (2,'The Legend of Zelda','Nintendo',1986,9.7,'Common','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (3,'Metroid','Nintendo',1986,9.2,'Common','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (4,'Donkey Kong','Nintendo',1986,8.9,'Common','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (5,'Castlevania','Konami',1987,9.0,'Common','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (6,'Mega Man','Capcom',1987,9.1,'Common','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (7,'Final Fantasy','Square',1987,9.3,'Common','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (8,'Ninja Gaiden','Tecmo',1988,9.4,'Common','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (9,'Super Mario Bros. 2','Nintendo',1988,9.0,'Common','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (10,'Zelda II: The Adventure of Link','Nintendo',1988,8.8,'Common','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (11,'DuckTales','Capcom',1989,9.2,'Common','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (12,'Mega Man 2','Capcom',1988,9.5,'Common','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (13,'Castlevania II: Simon''s Quest','Konami',1987,8.7,'Common','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (14,'Final Fantasy II','Square',1990,9.3,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (15,'Ninja Gaiden II: The Dark Sword of Chaos','Tecmo',1990,9.4,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (16,'Super Mario Bros. 3','Nintendo',1988,9.6,'Common','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (17,'The Legend of Zelda: Link''s Awakening','Nintendo',1993,9.5,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (18,'Metroid II: Return of Samus','Nintendo',1991,9.2,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (19,'Mega Man 3','Capcom',1990,9.1,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (20,'DuckTales 2','Capcom',1993,9.0,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (21,'Castlevania III: Dracula''s Curse','Konami',1990,9.3,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (22,'Final Fantasy III','Square',1990,9.5,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (23,'Ninja Gaiden III: The Ancient Ship of Doom','Tecmo',1990,9.2,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (24,'Super Mario All-Stars','Nintendo',1993,9.7,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (25,'The Legend of Zelda: Ocarina of Time','Nintendo',1998,9.8,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (26,'Metroid Fusion','Nintendo',2002,9.4,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (27,'Mega Man X','Capcom',1993,9.3,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (28,'DuckTales Remastered','Capcom',2013,9.0,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (29,'Castlevania: Symphony of the Night','Konami',1997,9.5,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (30,'Final Fantasy VII','Square',1997,9.7,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (31,'Ninja Gaiden Black','Tecmo',2005,9.2,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (32,'Super Mario Galaxy','Nintendo',2007,9.8,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (33,'The Legend of Zelda: Twilight Princess','Nintendo',2006,9.5,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (34,'Metroid Prime','Nintendo',2002,9.7,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (35,'Mega Man 9','Capcom',2008,9.3,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (36,'DuckTales 2 (Remastered)','Capcom',2013,9.0,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (37,'Castlevania: Lords of Shadow','Konami',2010,9.2,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (38,'Final Fantasy XIII','Square Enix',2009,9.0,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (39,'Ninja Gaiden II (2009)','Tecmo',2009,9.2,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (40,'Super Mario 3D Land','Nintendo',2011,9.5,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (41,'The Legend of Zelda: Skyward Sword','Nintendo',2011,9.2,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (42,'Metroid Prime Trilogy','Nintendo',2009,9.7,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (43,'Mega Man 10','Capcom',2010,9.1,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (44,'DuckTales Remastered (PS3)','Capcom',2013,9.0,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (45,'Castlevania: Mirror of Fate','Konami',2013,9.2,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (46,'Final Fantasy XIV','Square Enix',2010,9.0,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (47,'Ninja Gaiden Sigma 2','Tecmo',2009,9.2,'Rare','Hard');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (48,'Super Mario Odyssey','Nintendo',2017,9.8,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (49,'The Legend of Zelda: Breath of the Wild','Nintendo',2017,9.7,'Rare','Medium');
INSERT INTO game_info(id,name,publisher,year,rating,rarity,difficulty) VALUES (50,'Metroid Dread','Nintendo',2021,9.4,'Rare','Hard');
